// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package game

import (
	"context"

	"github.com/lardira/playtrack/internal/domain/game"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGameRepository creates a new instance of MockGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameRepository {
	mock := &MockGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGameRepository is an autogenerated mock type for the GameRepository type
type MockGameRepository struct {
	mock.Mock
}

type MockGameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameRepository) EXPECT() *MockGameRepository_Expecter {
	return &MockGameRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockGameRepository
func (_mock *MockGameRepository) FindAll(context1 context.Context) ([]game.Game, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []game.Game
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]game.Game, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []game.Game); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]game.Game)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockGameRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockGameRepository_Expecter) FindAll(context1 interface{}) *MockGameRepository_FindAll_Call {
	return &MockGameRepository_FindAll_Call{Call: _e.mock.On("FindAll", context1)}
}

func (_c *MockGameRepository_FindAll_Call) Run(run func(context1 context.Context)) *MockGameRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGameRepository_FindAll_Call) Return(games []game.Game, err error) *MockGameRepository_FindAll_Call {
	_c.Call.Return(games, err)
	return _c
}

func (_c *MockGameRepository_FindAll_Call) RunAndReturn(run func(context1 context.Context) ([]game.Game, error)) *MockGameRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type MockGameRepository
func (_mock *MockGameRepository) FindOne(ctx context.Context, id int) (*game.Game, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *game.Game
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*game.Game, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *game.Game); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockGameRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGameRepository_Expecter) FindOne(ctx interface{}, id interface{}) *MockGameRepository_FindOne_Call {
	return &MockGameRepository_FindOne_Call{Call: _e.mock.On("FindOne", ctx, id)}
}

func (_c *MockGameRepository_FindOne_Call) Run(run func(ctx context.Context, id int)) *MockGameRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepository_FindOne_Call) Return(game1 *game.Game, err error) *MockGameRepository_FindOne_Call {
	_c.Call.Return(game1, err)
	return _c
}

func (_c *MockGameRepository_FindOne_Call) RunAndReturn(run func(ctx context.Context, id int) (*game.Game, error)) *MockGameRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockGameRepository
func (_mock *MockGameRepository) Insert(context1 context.Context, game1 *game.Game) (int, error) {
	ret := _mock.Called(context1, game1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *game.Game) (int, error)); ok {
		return returnFunc(context1, game1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *game.Game) int); ok {
		r0 = returnFunc(context1, game1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *game.Game) error); ok {
		r1 = returnFunc(context1, game1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockGameRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - context1 context.Context
//   - game1 *game.Game
func (_e *MockGameRepository_Expecter) Insert(context1 interface{}, game1 interface{}) *MockGameRepository_Insert_Call {
	return &MockGameRepository_Insert_Call{Call: _e.mock.On("Insert", context1, game1)}
}

func (_c *MockGameRepository_Insert_Call) Run(run func(context1 context.Context, game1 *game.Game)) *MockGameRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *game.Game
		if args[1] != nil {
			arg1 = args[1].(*game.Game)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepository_Insert_Call) Return(n int, err error) *MockGameRepository_Insert_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockGameRepository_Insert_Call) RunAndReturn(run func(context1 context.Context, game1 *game.Game) (int, error)) *MockGameRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}
