// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package player

import (
	"context"

	"github.com/lardira/playtrack/internal/domain/game"
	"github.com/lardira/playtrack/internal/domain/player"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayerRepository creates a new instance of MockPlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerRepository {
	mock := &MockPlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayerRepository is an autogenerated mock type for the PlayerRepository type
type MockPlayerRepository struct {
	mock.Mock
}

type MockPlayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerRepository) EXPECT() *MockPlayerRepository_Expecter {
	return &MockPlayerRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) FindAll(context1 context.Context) ([]player.Player, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []player.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]player.Player, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []player.Player); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]player.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPlayerRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockPlayerRepository_Expecter) FindAll(context1 interface{}) *MockPlayerRepository_FindAll_Call {
	return &MockPlayerRepository_FindAll_Call{Call: _e.mock.On("FindAll", context1)}
}

func (_c *MockPlayerRepository_FindAll_Call) Run(run func(context1 context.Context)) *MockPlayerRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_FindAll_Call) Return(players []player.Player, err error) *MockPlayerRepository_FindAll_Call {
	_c.Call.Return(players, err)
	return _c
}

func (_c *MockPlayerRepository_FindAll_Call) RunAndReturn(run func(context1 context.Context) ([]player.Player, error)) *MockPlayerRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) FindOne(ctx context.Context, id string) (*player.Player, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *player.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*player.Player, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *player.Player); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*player.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockPlayerRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockPlayerRepository_Expecter) FindOne(ctx interface{}, id interface{}) *MockPlayerRepository_FindOne_Call {
	return &MockPlayerRepository_FindOne_Call{Call: _e.mock.On("FindOne", ctx, id)}
}

func (_c *MockPlayerRepository_FindOne_Call) Run(run func(ctx context.Context, id string)) *MockPlayerRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_FindOne_Call) Return(player1 *player.Player, err error) *MockPlayerRepository_FindOne_Call {
	_c.Call.Return(player1, err)
	return _c
}

func (_c *MockPlayerRepository_FindOne_Call) RunAndReturn(run func(ctx context.Context, id string) (*player.Player, error)) *MockPlayerRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) Insert(context1 context.Context, player1 *player.Player) (string, error) {
	ret := _mock.Called(context1, player1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.Player) (string, error)); ok {
		return returnFunc(context1, player1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.Player) string); ok {
		r0 = returnFunc(context1, player1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *player.Player) error); ok {
		r1 = returnFunc(context1, player1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockPlayerRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - context1 context.Context
//   - player1 *player.Player
func (_e *MockPlayerRepository_Expecter) Insert(context1 interface{}, player1 interface{}) *MockPlayerRepository_Insert_Call {
	return &MockPlayerRepository_Insert_Call{Call: _e.mock.On("Insert", context1, player1)}
}

func (_c *MockPlayerRepository_Insert_Call) Run(run func(context1 context.Context, player1 *player.Player)) *MockPlayerRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *player.Player
		if args[1] != nil {
			arg1 = args[1].(*player.Player)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_Insert_Call) Return(s string, err error) *MockPlayerRepository_Insert_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPlayerRepository_Insert_Call) RunAndReturn(run func(context1 context.Context, player1 *player.Player) (string, error)) *MockPlayerRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) Update(ctx context.Context, player1 *player.PlayerUpdate) (string, error) {
	ret := _mock.Called(ctx, player1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayerUpdate) (string, error)); ok {
		return returnFunc(ctx, player1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayerUpdate) string); ok {
		r0 = returnFunc(ctx, player1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *player.PlayerUpdate) error); ok {
		r1 = returnFunc(ctx, player1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlayerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - player1 *player.PlayerUpdate
func (_e *MockPlayerRepository_Expecter) Update(ctx interface{}, player1 interface{}) *MockPlayerRepository_Update_Call {
	return &MockPlayerRepository_Update_Call{Call: _e.mock.On("Update", ctx, player1)}
}

func (_c *MockPlayerRepository_Update_Call) Run(run func(ctx context.Context, player1 *player.PlayerUpdate)) *MockPlayerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *player.PlayerUpdate
		if args[1] != nil {
			arg1 = args[1].(*player.PlayerUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_Update_Call) Return(s string, err error) *MockPlayerRepository_Update_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPlayerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, player1 *player.PlayerUpdate) (string, error)) *MockPlayerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayedGameRepository creates a new instance of MockPlayedGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayedGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayedGameRepository {
	mock := &MockPlayedGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayedGameRepository is an autogenerated mock type for the PlayedGameRepository type
type MockPlayedGameRepository struct {
	mock.Mock
}

type MockPlayedGameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayedGameRepository) EXPECT() *MockPlayedGameRepository_Expecter {
	return &MockPlayedGameRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockPlayedGameRepository
func (_mock *MockPlayedGameRepository) FindAll(ctx context.Context, playerID string) ([]player.PlayedGame, error) {
	ret := _mock.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []player.PlayedGame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]player.PlayedGame, error)); ok {
		return returnFunc(ctx, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []player.PlayedGame); ok {
		r0 = returnFunc(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]player.PlayedGame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayedGameRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPlayedGameRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID string
func (_e *MockPlayedGameRepository_Expecter) FindAll(ctx interface{}, playerID interface{}) *MockPlayedGameRepository_FindAll_Call {
	return &MockPlayedGameRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx, playerID)}
}

func (_c *MockPlayedGameRepository_FindAll_Call) Run(run func(ctx context.Context, playerID string)) *MockPlayedGameRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayedGameRepository_FindAll_Call) Return(playedGames []player.PlayedGame, err error) *MockPlayedGameRepository_FindAll_Call {
	_c.Call.Return(playedGames, err)
	return _c
}

func (_c *MockPlayedGameRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context, playerID string) ([]player.PlayedGame, error)) *MockPlayedGameRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindLast provides a mock function for the type MockPlayedGameRepository
func (_mock *MockPlayedGameRepository) FindLast(ctx context.Context, playerID string) (*player.PlayedGame, error) {
	ret := _mock.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for FindLast")
	}

	var r0 *player.PlayedGame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*player.PlayedGame, error)); ok {
		return returnFunc(ctx, playerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *player.PlayedGame); ok {
		r0 = returnFunc(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*player.PlayedGame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayedGameRepository_FindLast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindLast'
type MockPlayedGameRepository_FindLast_Call struct {
	*mock.Call
}

// FindLast is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID string
func (_e *MockPlayedGameRepository_Expecter) FindLast(ctx interface{}, playerID interface{}) *MockPlayedGameRepository_FindLast_Call {
	return &MockPlayedGameRepository_FindLast_Call{Call: _e.mock.On("FindLast", ctx, playerID)}
}

func (_c *MockPlayedGameRepository_FindLast_Call) Run(run func(ctx context.Context, playerID string)) *MockPlayedGameRepository_FindLast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayedGameRepository_FindLast_Call) Return(playedGame *player.PlayedGame, err error) *MockPlayedGameRepository_FindLast_Call {
	_c.Call.Return(playedGame, err)
	return _c
}

func (_c *MockPlayedGameRepository_FindLast_Call) RunAndReturn(run func(ctx context.Context, playerID string) (*player.PlayedGame, error)) *MockPlayedGameRepository_FindLast_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type MockPlayedGameRepository
func (_mock *MockPlayedGameRepository) FindOne(ctx context.Context, playerID string, id int) (*player.PlayedGame, error) {
	ret := _mock.Called(ctx, playerID, id)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *player.PlayedGame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*player.PlayedGame, error)); ok {
		return returnFunc(ctx, playerID, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *player.PlayedGame); ok {
		r0 = returnFunc(ctx, playerID, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*player.PlayedGame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, playerID, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayedGameRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockPlayedGameRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID string
//   - id int
func (_e *MockPlayedGameRepository_Expecter) FindOne(ctx interface{}, playerID interface{}, id interface{}) *MockPlayedGameRepository_FindOne_Call {
	return &MockPlayedGameRepository_FindOne_Call{Call: _e.mock.On("FindOne", ctx, playerID, id)}
}

func (_c *MockPlayedGameRepository_FindOne_Call) Run(run func(ctx context.Context, playerID string, id int)) *MockPlayedGameRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlayedGameRepository_FindOne_Call) Return(playedGame *player.PlayedGame, err error) *MockPlayedGameRepository_FindOne_Call {
	_c.Call.Return(playedGame, err)
	return _c
}

func (_c *MockPlayedGameRepository_FindOne_Call) RunAndReturn(run func(ctx context.Context, playerID string, id int) (*player.PlayedGame, error)) *MockPlayedGameRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockPlayedGameRepository
func (_mock *MockPlayedGameRepository) Insert(ctx context.Context, player1 *player.PlayedGame) (int, error) {
	ret := _mock.Called(ctx, player1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayedGame) (int, error)); ok {
		return returnFunc(ctx, player1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayedGame) int); ok {
		r0 = returnFunc(ctx, player1)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *player.PlayedGame) error); ok {
		r1 = returnFunc(ctx, player1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayedGameRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockPlayedGameRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - player1 *player.PlayedGame
func (_e *MockPlayedGameRepository_Expecter) Insert(ctx interface{}, player1 interface{}) *MockPlayedGameRepository_Insert_Call {
	return &MockPlayedGameRepository_Insert_Call{Call: _e.mock.On("Insert", ctx, player1)}
}

func (_c *MockPlayedGameRepository_Insert_Call) Run(run func(ctx context.Context, player1 *player.PlayedGame)) *MockPlayedGameRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *player.PlayedGame
		if args[1] != nil {
			arg1 = args[1].(*player.PlayedGame)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayedGameRepository_Insert_Call) Return(n int, err error) *MockPlayedGameRepository_Insert_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPlayedGameRepository_Insert_Call) RunAndReturn(run func(ctx context.Context, player1 *player.PlayedGame) (int, error)) *MockPlayedGameRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPlayedGameRepository
func (_mock *MockPlayedGameRepository) Update(ctx context.Context, game *player.PlayedGameUpdate) (string, error) {
	ret := _mock.Called(ctx, game)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayedGameUpdate) (string, error)); ok {
		return returnFunc(ctx, game)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayedGameUpdate) string); ok {
		r0 = returnFunc(ctx, game)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *player.PlayedGameUpdate) error); ok {
		r1 = returnFunc(ctx, game)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayedGameRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlayedGameRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - game *player.PlayedGameUpdate
func (_e *MockPlayedGameRepository_Expecter) Update(ctx interface{}, game interface{}) *MockPlayedGameRepository_Update_Call {
	return &MockPlayedGameRepository_Update_Call{Call: _e.mock.On("Update", ctx, game)}
}

func (_c *MockPlayedGameRepository_Update_Call) Run(run func(ctx context.Context, game *player.PlayedGameUpdate)) *MockPlayedGameRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *player.PlayedGameUpdate
		if args[1] != nil {
			arg1 = args[1].(*player.PlayedGameUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayedGameRepository_Update_Call) Return(s string, err error) *MockPlayedGameRepository_Update_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPlayedGameRepository_Update_Call) RunAndReturn(run func(ctx context.Context, game *player.PlayedGameUpdate) (string, error)) *MockPlayedGameRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGameRepository creates a new instance of MockGameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGameRepository {
	mock := &MockGameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGameRepository is an autogenerated mock type for the GameRepository type
type MockGameRepository struct {
	mock.Mock
}

type MockGameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGameRepository) EXPECT() *MockGameRepository_Expecter {
	return &MockGameRepository_Expecter{mock: &_m.Mock}
}

// FindOne provides a mock function for the type MockGameRepository
func (_mock *MockGameRepository) FindOne(ctx context.Context, id int) (*game.Game, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *game.Game
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (*game.Game, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) *game.Game); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*game.Game)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGameRepository_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type MockGameRepository_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockGameRepository_Expecter) FindOne(ctx interface{}, id interface{}) *MockGameRepository_FindOne_Call {
	return &MockGameRepository_FindOne_Call{Call: _e.mock.On("FindOne", ctx, id)}
}

func (_c *MockGameRepository_FindOne_Call) Run(run func(ctx context.Context, id int)) *MockGameRepository_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGameRepository_FindOne_Call) Return(game1 *game.Game, err error) *MockGameRepository_FindOne_Call {
	_c.Call.Return(game1, err)
	return _c
}

func (_c *MockGameRepository_FindOne_Call) RunAndReturn(run func(ctx context.Context, id int) (*game.Game, error)) *MockGameRepository_FindOne_Call {
	_c.Call.Return(run)
	return _c
}
