// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/lardira/playtrack/internal/domain/player"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlayerRepository creates a new instance of MockPlayerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerRepository {
	mock := &MockPlayerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlayerRepository is an autogenerated mock type for the PlayerRepository type
type MockPlayerRepository struct {
	mock.Mock
}

type MockPlayerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerRepository) EXPECT() *MockPlayerRepository_Expecter {
	return &MockPlayerRepository_Expecter{mock: &_m.Mock}
}

// FindOneByUsername provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) FindOneByUsername(ctx context.Context, username string) (*player.Player, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindOneByUsername")
	}

	var r0 *player.Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*player.Player, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *player.Player); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*player.Player)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_FindOneByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOneByUsername'
type MockPlayerRepository_FindOneByUsername_Call struct {
	*mock.Call
}

// FindOneByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockPlayerRepository_Expecter) FindOneByUsername(ctx interface{}, username interface{}) *MockPlayerRepository_FindOneByUsername_Call {
	return &MockPlayerRepository_FindOneByUsername_Call{Call: _e.mock.On("FindOneByUsername", ctx, username)}
}

func (_c *MockPlayerRepository_FindOneByUsername_Call) Run(run func(ctx context.Context, username string)) *MockPlayerRepository_FindOneByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_FindOneByUsername_Call) Return(player1 *player.Player, err error) *MockPlayerRepository_FindOneByUsername_Call {
	_c.Call.Return(player1, err)
	return _c
}

func (_c *MockPlayerRepository_FindOneByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*player.Player, error)) *MockPlayerRepository_FindOneByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) Insert(context1 context.Context, player1 *player.Player) (string, error) {
	ret := _mock.Called(context1, player1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.Player) (string, error)); ok {
		return returnFunc(context1, player1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.Player) string); ok {
		r0 = returnFunc(context1, player1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *player.Player) error); ok {
		r1 = returnFunc(context1, player1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockPlayerRepository_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - context1 context.Context
//   - player1 *player.Player
func (_e *MockPlayerRepository_Expecter) Insert(context1 interface{}, player1 interface{}) *MockPlayerRepository_Insert_Call {
	return &MockPlayerRepository_Insert_Call{Call: _e.mock.On("Insert", context1, player1)}
}

func (_c *MockPlayerRepository_Insert_Call) Run(run func(context1 context.Context, player1 *player.Player)) *MockPlayerRepository_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *player.Player
		if args[1] != nil {
			arg1 = args[1].(*player.Player)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_Insert_Call) Return(s string, err error) *MockPlayerRepository_Insert_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPlayerRepository_Insert_Call) RunAndReturn(run func(context1 context.Context, player1 *player.Player) (string, error)) *MockPlayerRepository_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPlayerRepository
func (_mock *MockPlayerRepository) Update(ctx context.Context, player1 *player.PlayerUpdate) (string, error) {
	ret := _mock.Called(ctx, player1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayerUpdate) (string, error)); ok {
		return returnFunc(ctx, player1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *player.PlayerUpdate) string); ok {
		r0 = returnFunc(ctx, player1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *player.PlayerUpdate) error); ok {
		r1 = returnFunc(ctx, player1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlayerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPlayerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - player1 *player.PlayerUpdate
func (_e *MockPlayerRepository_Expecter) Update(ctx interface{}, player1 interface{}) *MockPlayerRepository_Update_Call {
	return &MockPlayerRepository_Update_Call{Call: _e.mock.On("Update", ctx, player1)}
}

func (_c *MockPlayerRepository_Update_Call) Run(run func(ctx context.Context, player1 *player.PlayerUpdate)) *MockPlayerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *player.PlayerUpdate
		if args[1] != nil {
			arg1 = args[1].(*player.PlayerUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlayerRepository_Update_Call) Return(s string, err error) *MockPlayerRepository_Update_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockPlayerRepository_Update_Call) RunAndReturn(run func(ctx context.Context, player1 *player.PlayerUpdate) (string, error)) *MockPlayerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
